Name: Build documentation
description: Build the QUEENS documentation with sphinx

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Create Python environment
      id: environment
      uses: ./.github/actions/create_python_environment
    - name: Sphinx build
      shell: bash -l {0}
      env:
        PYTHON_PACKAGE_MANAGER: ${{steps.environment.outputs.ppm}}
      run: |
        $PYTHON_PACKAGE_MANAGER activate queens
        sphinx-apidoc -o doc/source queens -f -M
        cd doc
        sphinx-build -b html -d build/doctrees source build/html
    - name: Upload html
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc/build/html
        retention-days: 1
